# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created: Sun Feb 18 01:16:20 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Prism_v2(object):
    def setupUi(self, Prism_v2):
        Prism_v2.setObjectName("Prism_v2")
        Prism_v2.resize(447, 657)
        Prism_v2.setFixedSize(447, 657)
        self.centralwidget = QtGui.QWidget(Prism_v2)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 427, 578))
        self.tabs.setObjectName("tabs")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 19, 525))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(10, 525, 401, 17))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.sell_button = QtGui.QPushButton(self.tab_2)
        self.sell_button.setGeometry(QtCore.QRect(20, 112, 382, 34))
        self.sell_button.setObjectName("sell_button")
        self.stop_button = QtGui.QPushButton(self.tab_2)
        self.stop_button.setGeometry(QtCore.QRect(215, 70, 187, 34))
        self.stop_button.setObjectName("stop_button")
        self.start_button = QtGui.QPushButton(self.tab_2)
        self.start_button.setGeometry(QtCore.QRect(19, 70, 188, 34))
        self.start_button.setObjectName("start_button")
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(10, 0, 403, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_6 = QtGui.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(403, 10, 21, 525))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.select_exchange = QtGui.QComboBox(self.tab_2)
        self.select_exchange.setGeometry(QtCore.QRect(170, 20, 231, 31))
        self.select_exchange.setObjectName("select_exchange")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 160, 381, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.bot_log = QtGui.QGridLayout(self.gridLayoutWidget)
        self.bot_log.setContentsMargins(0, 0, 0, 0)
        self.bot_log.setObjectName("bot_log")
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.line_10 = QtGui.QFrame(self.tab_3)
        self.line_10.setGeometry(QtCore.QRect(0, 10, 19, 525))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_12 = QtGui.QFrame(self.tab_3)
        self.line_12.setGeometry(QtCore.QRect(10, 0, 401, 21))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_15 = QtGui.QFrame(self.tab_3)
        self.line_15.setGeometry(QtCore.QRect(10, 525, 401, 21))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 380, 21))
        self.label_3.setObjectName("label_3")
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(20, 240, 380, 31))
        self.label_20.setObjectName("label_20")
        self.blacklist_table = QtGui.QTableWidget(self.tab_3)
        self.blacklist_table.setGeometry(QtCore.QRect(20, 274, 380, 165))
        self.blacklist_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.blacklist_table.setAutoScroll(True)
        self.blacklist_table.setTabKeyNavigation(True)
        self.blacklist_table.setProperty("showDropIndicator", False)
        self.blacklist_table.setDragEnabled(True)
        self.blacklist_table.setDragDropOverwriteMode(True)
        self.blacklist_table.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.blacklist_table.setShowGrid(True)
        self.blacklist_table.setWordWrap(True)
        self.blacklist_table.setCornerButtonEnabled(True)
        self.blacklist_table.setColumnCount(3)
        self.blacklist_table.setObjectName("blacklist_table")
        self.blacklist_table.setColumnCount(3)
        self.blacklist_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.blacklist_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.blacklist_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.blacklist_table.setHorizontalHeaderItem(2, item)
        self.blacklist_table.horizontalHeader().setStretchLastSection(True)
        self.blacklist_table.verticalHeader().setHighlightSections(True)
        self.blacklist_table.verticalHeader().setSortIndicatorShown(False)
        self.line_16 = QtGui.QFrame(self.tab_3)
        self.line_16.setGeometry(QtCore.QRect(403, 10, 21, 525))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.add_blacklist = QtGui.QPushButton(self.tab_3)
        self.add_blacklist.setGeometry(QtCore.QRect(288, 450, 112, 34))
        self.add_blacklist.setObjectName("add_blacklist")
        self.blacklist_exchange = QtGui.QComboBox(self.tab_3)
        self.blacklist_exchange.setGeometry(QtCore.QRect(193, 454, 84, 27))
        self.blacklist_exchange.setObjectName("blacklist_exchange")
        self.blacklist_exchange.addItem("")
        self.coin_blacklist = QtGui.QLineEdit(self.tab_3)
        self.coin_blacklist.setGeometry(QtCore.QRect(20, 454, 161, 27))
        self.coin_blacklist.setObjectName("coin_blacklist")
        self.line_14 = QtGui.QFrame(self.tab_3)
        self.line_14.setGeometry(QtCore.QRect(10, 224, 400, 21))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 50, 381, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settings_key = QtGui.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_key.sizePolicy().hasHeightForWidth())
        self.settings_key.setSizePolicy(sizePolicy)
        self.settings_key.setObjectName("settings_key")
        self.gridLayout_2.addWidget(self.settings_key, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.settings_secret = QtGui.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_secret.sizePolicy().hasHeightForWidth())
        self.settings_secret.setSizePolicy(sizePolicy)
        self.settings_secret.setObjectName("settings_secret")
        self.gridLayout_2.addWidget(self.settings_secret, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.settings_key_2 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_key_2.sizePolicy().hasHeightForWidth())
        self.settings_key_2.setSizePolicy(sizePolicy)
        self.settings_key_2.setObjectName("settings_key_2")
        self.gridLayout_2.addWidget(self.settings_key_2, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.save_exchange = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.save_exchange.setObjectName("save_exchange")
        self.gridLayout.addWidget(self.save_exchange, 2, 0, 1, 1)
        self.key_value = QtGui.QLabel(self.tab_3)
        self.key_value.setGeometry(QtCore.QRect(470, 460, 331, 21))
        self.key_value.setText("")
        self.key_value.setObjectName("key_value")
        self.secret_value = QtGui.QLabel(self.tab_3)
        self.secret_value.setGeometry(QtCore.QRect(490, 490, 311, 21))
        self.secret_value.setText("")
        self.secret_value.setObjectName("secret_value")
        self.verification = QtGui.QLabel(self.tab_3)
        self.verification.setGeometry(QtCore.QRect(208, 500, 191, 21))
        self.verification.setObjectName("verification")
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 500, 180, 21))
        self.label_15.setObjectName("label_15")
        self.tabs.addTab(self.tab_3, "")
        Prism_v2.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Prism_v2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 31))
        self.menubar.setObjectName("menubar")
        self.menuPrism_v2 = QtGui.QMenu(self.menubar)
        self.menuPrism_v2.setObjectName("menuPrism_v2")
        Prism_v2.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Prism_v2)
        self.statusbar.setObjectName("statusbar")
        Prism_v2.setStatusBar(self.statusbar)
        self.actionV1_0_0 = QtGui.QAction(Prism_v2)
        self.actionV1_0_0.setObjectName("actionV1_0_0")
        self.menubar.addAction(self.menuPrism_v2.menuAction())

        self.retranslateUi(Prism_v2)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Prism_v2)
        Prism_v2.setTabOrder(self.tabs, self.select_exchange)
        Prism_v2.setTabOrder(self.select_exchange, self.start_button)
        Prism_v2.setTabOrder(self.start_button, self.stop_button)
        Prism_v2.setTabOrder(self.stop_button, self.sell_button)
        Prism_v2.setTabOrder(self.sell_button, self.settings_key)
        Prism_v2.setTabOrder(self.settings_key, self.settings_secret)
        Prism_v2.setTabOrder(self.settings_secret, self.save_exchange)
        Prism_v2.setTabOrder(self.save_exchange, self.blacklist_table)
        Prism_v2.setTabOrder(self.blacklist_table, self.coin_blacklist)
        Prism_v2.setTabOrder(self.coin_blacklist, self.blacklist_exchange)
        Prism_v2.setTabOrder(self.blacklist_exchange, self.add_blacklist)

    def retranslateUi(self, Prism_v2):
        Prism_v2.setWindowTitle(QtGui.QApplication.translate("Prism_v2", "Prism_v2", None, QtGui.QApplication.UnicodeUTF8))
        self.sell_button.setText(QtGui.QApplication.translate("Prism_v2", "Sell Everything", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("Prism_v2", "Stop Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("Prism_v2", "Start Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Prism_v2", "Select Exchange : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QtGui.QApplication.translate("Prism_v2", "Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Prism_v2", "Exchange Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Prism_v2", "Blacklisted Coins", None, QtGui.QApplication.UnicodeUTF8))
        self.blacklist_table.setSortingEnabled(False)
        self.blacklist_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Prism_v2", "Coin", None, QtGui.QApplication.UnicodeUTF8))
        self.blacklist_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Prism_v2", "Exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.blacklist_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Prism_v2", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.add_blacklist.setText(QtGui.QApplication.translate("Prism_v2", "Add Coin", None, QtGui.QApplication.UnicodeUTF8))
        self.blacklist_exchange.setItemText(0, QtGui.QApplication.translate("Prism_v2", "Bittrex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Prism_v2", "Bittrex Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Prism_v2", "BTC # per Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Prism_v2", "Bittrex Secret", None, QtGui.QApplication.UnicodeUTF8))
        self.save_exchange.setText(QtGui.QApplication.translate("Prism_v2", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.verification.setText(QtGui.QApplication.translate("Prism_v2", "FAILED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Prism_v2", "Key/Secret Verification:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QtGui.QApplication.translate("Prism_v2", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPrism_v2.setTitle(QtGui.QApplication.translate("Prism_v2", "v1.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionV1_0_0.setText(QtGui.QApplication.translate("Prism_v2", "v1.0.0", None, QtGui.QApplication.UnicodeUTF8))

